blank_issues_enabled: true
contact_links:
  - name: Domanda
    url: https://github.com/ondata/guidaVisiData/discussions
    about: Per favore fai qui le tue domande su Material for MkDocs. Se invece devi segnalare un problema o fare una proposta per il codice di questo repo, apri una [issue](https://github.com/opendatasicilia/ods-mkdocs-material/issues).
